import type { DemoScenario, EvidenceSource } from '../types';

export const paradipEvidenceSources: EvidenceSource[] = [
  {
    id: 'isro-oceansat3-paradip',
    sourceName: 'ISRO Earth Observation (Oceansat-3 / EOS-06)',
    institution: 'Indian Space Research Organisation (ISRO)',
    dataType: 'Scatterometer Ocean Surface Vector Winds (OSVW)',
    sensor: 'Ku-band Scatterometer (OSCAT-3)',
    timestamp: '2026-10-01 05:30 IST Cycle (18m ago)',
    status: 'Verified',
    relevance: 96,
    reliability: 98,
    resolution: '12.5 km spatial grid • 6-hr revisit',
    parameters: ['Surface Wind Vectors (18.4 kt)', 'Wind Direction (068° ENE)', 'Atmospheric Liquid Water'],
    snippet: 'OSCAT-3 swath pass over North Bay of Bengal confirms sustained ENE wind fields at 18-22 knots with localized gusts to 24 knots in Paradip offshore sector.',
  },
  {
    id: 'incois-swan-paradip',
    sourceName: 'INCOIS Marine Forecast (SWAN / WaveWatch III)',
    institution: 'Indian National Centre for Ocean Information Services (INCOIS)',
    dataType: 'Operational Wave Simulation & High Wave Alert Layer',
    sensor: 'Numerical Model / Coastal ADCP Wave Array',
    timestamp: '2026-10-01 05:45 IST Cycle (12m ago)',
    status: 'Synchronized',
    relevance: 94,
    reliability: 95,
    resolution: '0.05° Coastal High-Resolution Mesh',
    parameters: ['Significant Wave Height (Hs: 1.8 m)', 'Peak Period (Tp: 8.2 s)', 'Swell Direction (SE 135°)'],
    snippet: 'Simulated boundary wave conditions indicate moderate swell (1.6m–2.1m) propagating from SE, crossing coastal wind waves generated by prevailing ENE breeze off Odisha.',
  },
  {
    id: 'imd-dwr-paradip',
    sourceName: 'IMD Doppler Weather Radar Paradip',
    institution: 'India Meteorological Department (IMD)',
    dataType: 'Polarimetric Atmospheric Reflectivity & Squall Detection',
    sensor: 'S-band Doppler Weather Radar (DWR Paradip)',
    timestamp: '2026-10-01 05:50 IST Scan (7m ago)',
    status: 'Synchronized',
    relevance: 88,
    reliability: 92,
    resolution: '250 m radial bin • 10-minute sweep',
    parameters: ['Reflectivity (Z < 28 dBZ)', 'Echo Tops (< 4.5 km)', 'Precipitation Velocity (-4 m/s)'],
    snippet: 'No convective squall cells or meso-cyclonic signatures identified within 150 km radius. Light stratiform clouds; horizontal visibility 8–10 km.',
  },
  {
    id: 'incois-cb02-buoy',
    sourceName: 'Coastal Met-Ocean Buoy (CB-02 Paradip)',
    institution: 'National Institute of Ocean Technology (NIOT) / INCOIS',
    dataType: 'In-situ Moored Oceanographic Telemetry',
    sensor: 'Acoustic Doppler Current Profiler (ADCP) & CTD Sensor',
    timestamp: '2026-10-01 05:55 IST Stream (2m ago)',
    status: 'Synchronized',
    relevance: 91,
    reliability: 97,
    resolution: 'Point Sensor (20°14.8\'N, 86°43.2\'E)',
    parameters: ['Sea Surface Temp (28.4°C)', 'Subsurface Current (0.8 kt southward)', 'Barometric Pressure (1012.8 hPa)'],
    snippet: 'In-situ real-time validation corroborates 1.76m wave height and stable barometric trend over last 6 hours off Paradip port.',
  },
  {
    id: 'nho-paradip-chart',
    sourceName: 'NHO Hydrographic Navigation Chart (IN 3010)',
    institution: 'National Hydrographic Office, Dehradun',
    dataType: 'Bathymetric Depth Contours & Nautical Obstruction Layer',
    sensor: 'Multibeam Sonar Survey Data',
    timestamp: 'Electronic Navigational Chart (ENC) Edition 2026',
    status: 'Verified',
    relevance: 85,
    reliability: 99,
    resolution: '1:50,000 Coastal Navigational Scale',
    parameters: ['Dredged Channel (17.1m depth)', 'Inner Shelf Gradient', 'Mahanadi Spit Shoal Morphology'],
    snippet: 'Main navigation channel maintains safe draft; Mahanadi sand spit shoaling active up to 1.8 nautical miles east of False Point lighthouse.',
  }
];

export const kochiEvidenceSources: EvidenceSource[] = [
  {
    id: 'isro-oceansat3-kochi',
    sourceName: 'ISRO Earth Observation (Oceansat-3 / EOS-06)',
    institution: 'Indian Space Research Organisation (ISRO)',
    dataType: 'Scatterometer Ocean Surface Vector Winds (OSVW)',
    sensor: 'Ku-band Scatterometer (OSCAT-3)',
    timestamp: '2026-10-01 05:25 IST Cycle (23m ago)',
    status: 'Verified',
    relevance: 95,
    reliability: 98,
    resolution: '12.5 km spatial grid • 6-hr revisit',
    parameters: ['Surface Wind Vectors (15.2 kt inner / 23.6 kt outer)', 'Wind Direction (310° NW)', 'Atmospheric Liquid Water'],
    snippet: 'OSCAT-3 Arabian Sea swath confirms distinct wind shear gradient: sheltered 14-17 kt winds along Kochi coastal shelf, escalating to 24-28 kt gusts in open deep sea beyond 15 NM.',
  },
  {
    id: 'incois-swan-kochi',
    sourceName: 'INCOIS High-Resolution Wave Forecast (SWAN Arabian Sea)',
    institution: 'Indian National Centre for Ocean Information Services (INCOIS)',
    dataType: 'Operational Wave Simulation & High Wave Alert Layer',
    sensor: 'Numerical Model / Coastal Wave Array',
    timestamp: '2026-10-01 05:40 IST Cycle (17m ago)',
    status: 'Synchronized',
    relevance: 96,
    reliability: 96,
    resolution: '0.025° High-Resolution Coastal Grid (Kerala Shelf)',
    parameters: ['Inner Shelf Hs (1.35m)', 'Outer Shelf Hs (2.55m)', 'Peak Period (8.6s)', 'Swell Direction (235° WSW)'],
    snippet: 'SWAN simulation indicates strong bathymetric wave attenuation along Kochi 25m contour (Route A). Open-ocean Route B suffers steep cross-sea resonance with 52° roll angle.',
  },
  {
    id: 'imd-dwr-kochi',
    sourceName: 'IMD Doppler Weather Radar Kochi',
    institution: 'India Meteorological Department (IMD)',
    dataType: 'Polarimetric Atmospheric Reflectivity & Squall Surveillance',
    sensor: 'C-band Doppler Weather Radar (DWR Kochi)',
    timestamp: '2026-10-01 05:50 IST Scan (7m ago)',
    status: 'Synchronized',
    relevance: 89,
    reliability: 94,
    resolution: '250 m radial bin • 10-minute sweep',
    parameters: ['Reflectivity (Z < 24 dBZ)', 'Echo Tops (< 3.8 km)', 'Precipitation Velocity (-2 m/s)'],
    snippet: 'Zero organized convective squall clusters over Kochi approaches. Moderate sea-breeze convergence line developing 12 NM offshore during mid-afternoon.',
  },
  {
    id: 'niot-ad06-buoy',
    sourceName: 'Coastal Oceanographic Buoy (AD-06 Kochi)',
    institution: 'National Institute of Ocean Technology (NIOT) / INCOIS',
    dataType: 'In-situ Moored Oceanographic Telemetry',
    sensor: 'Acoustic Doppler Current Profiler (ADCP) & CTD Sensor',
    timestamp: '2026-10-01 05:54 IST Stream (3m ago)',
    status: 'Synchronized',
    relevance: 93,
    reliability: 97,
    resolution: 'Point Sensor (09°58.2\'N, 76°11.4\'E)',
    parameters: ['Sea Surface Temp (29.1°C)', 'Subsurface Current (0.7 kt south-southeast)', 'Wave Height (1.38m)'],
    snippet: 'In-situ ADCP buoy off Kochi harbour outer fairway confirms mild 1.38m wave heights and predictable southward coastal drift inside the 30m depth contour.',
  },
  {
    id: 'nho-kochi-chart',
    sourceName: 'NHO Hydrographic Navigation Chart (IN 2004 / 220)',
    institution: 'National Hydrographic Office, Dehradun',
    dataType: 'Bathymetric Depth Contours & Nautical Obstruction Layer',
    sensor: 'Multibeam Sonar Survey Data',
    timestamp: 'Electronic Navigational Chart (ENC) Edition 2026',
    status: 'Verified',
    relevance: 92,
    reliability: 99,
    resolution: '1:60,000 Coastal Navigational Scale',
    parameters: ['Fairway Channel (16.2m depth)', 'Malabar Inner Shelf Profile', 'Vypin Coastal Banks'],
    snippet: 'Kochi approach fairway clear with maintained 16.2m draft; Route A corridor safely follows the 25m depth contour clear of shallow sandbanks.',
  }
];

export const vizagEvidenceSources: EvidenceSource[] = [
  {
    id: 'isro-oceansat3-vizag',
    sourceName: 'ISRO Earth Observation (Oceansat-3 / EOS-06)',
    institution: 'Indian Space Research Organisation (ISRO)',
    dataType: 'Scatterometer Ocean Surface Vector Winds (OSVW)',
    sensor: 'Ku-band Scatterometer (OSCAT-3)',
    timestamp: '2026-10-01 05:32 IST Cycle (16m ago)',
    status: 'Verified',
    relevance: 95,
    reliability: 98,
    resolution: '12.5 km spatial grid • 6-hr revisit',
    parameters: ['Surface Wind Vectors (17.5 kt)', 'Wind Direction (190° SSW)', 'Atmospheric Liquid Water'],
    snippet: 'OSCAT-3 pass over Central Bay of Bengal confirms uniform south-southwesterly airflow across Andhra coast. Zero cyclonic curvature or vortex depression detected.',
  },
  {
    id: 'incois-hazard-vizag',
    sourceName: 'INCOIS Marine Early Warning System (INCOIS Hyderabad)',
    institution: 'Indian National Centre for Ocean Information Services (INCOIS)',
    dataType: 'Multi-Hazard Threat Matrix & Coastal Surge Simulation',
    sensor: 'Numerical Model / Tsunami Warning Network',
    timestamp: '2026-10-01 05:45 IST Cycle (13m ago)',
    status: 'Synchronized',
    relevance: 97,
    reliability: 96,
    resolution: '0.02° Coastal Threat Mesh',
    parameters: ['Storm Surge Anomaly (+0.06m)', 'Astronomical Tide (1.42m)', 'Tsunami Sensor Health (100%)'],
    snippet: 'Comprehensive threat screening confirms zero cyclone warnings, zero tsunami anomalies, and normal astronomical tide cycles along Visakhapatnam coastline.',
  },
  {
    id: 'imd-dwr-vizag',
    sourceName: 'IMD Doppler Weather Radar Kailasagiri (Visakhapatnam)',
    institution: 'India Meteorological Department (IMD)',
    dataType: 'Polarimetric Atmospheric Reflectivity & Squall Surveillance',
    sensor: 'S-band Doppler Weather Radar (DWR Kailasagiri)',
    timestamp: '2026-10-01 05:52 IST Scan (5m ago)',
    status: 'Synchronized',
    relevance: 91,
    reliability: 95,
    resolution: '250 m radial bin • 10-minute sweep',
    parameters: ['Reflectivity (Z < 26 dBZ)', 'Echo Tops (< 4.0 km)', 'Convective Velocity (-3 m/s)'],
    snippet: 'Clear atmospheric scan across 250 km radius. Absence of convective squall lines or severe meso-scale storms approaching Visakhapatnam Port.',
  },
  {
    id: 'incois-bd11-buoy',
    sourceName: 'Deep Ocean Met-Ocean Buoy (BD-11 off Vizag)',
    institution: 'National Institute of Ocean Technology (NIOT) / INCOIS',
    dataType: 'In-situ Moored Oceanographic Telemetry',
    sensor: 'Deep Ocean Acoustic Profiler & Meteorological Sensor Array',
    timestamp: '2026-10-01 05:56 IST Stream (1m ago)',
    status: 'Synchronized',
    relevance: 94,
    reliability: 97,
    resolution: 'Point Sensor (17°38.5\'N, 83°32.1\'E)',
    parameters: ['Sea Surface Temp (28.6°C)', 'Significant Wave Height (1.72m)', 'Barometric Pressure (1011.6 hPa)'],
    snippet: 'Moored buoy BD-11 records stable 1.72m swell and steady barometric conditions in Visakhapatnam offshore roadstead.',
  },
  {
    id: 'nho-vizag-chart',
    sourceName: 'NHO Hydrographic Navigation Chart (IN 3002)',
    institution: 'National Hydrographic Office, Dehradun',
    dataType: 'Bathymetric Depth Contours & Nautical Obstruction Layer',
    sensor: 'Multibeam Sonar Survey Data',
    timestamp: 'Electronic Navigational Chart (ENC) Edition 2026',
    status: 'Verified',
    relevance: 88,
    reliability: 99,
    resolution: '1:25,000 Port & Roadstead Navigational Scale',
    parameters: ['Dolphin\'s Nose Headland Profile', 'Outer Harbour Basin (20.0m depth)', 'Rishikonda Shoals'],
    snippet: 'Natural deepwater entrance channel maintains unobstructed 20m depth; tidal current acceleration verified around Dolphin\'s Nose promontory.',
  }
];

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  scenario1: {
    id: 'scenario1',
    title: 'Fishing Safety Assessment — Paradip Coast',
    chipLabel: 'Fishing safety',
    canonicalQuery: 'Is it safe to fish near Paradip tomorrow morning?',
    queryAliases: [
      'is it safe to fish near paradip tomorrow morning',
      'is it safe to fish near paradip tomorrow',
      'fishing safety paradip',
      'can we go fishing tomorrow morning paradip',
      'paradip fishing weather tomorrow',
      'sea safety fishing paradip',
      'fishing paradip',
      'safe to fish paradip'
    ],
    context: {
      intent: 'Marine Safety & Advisory Evaluation',
      location: 'Paradip Coastal Waters, Odisha',
      coordinates: '20.2644° N, 86.6710° E (0–12 NM)',
      timeWindow: 'Tomorrow Morning (05:00 – 11:30 IST)',
      activity: 'Artisanal & Mechanized Coastal Fishing',
      scope: ['Atmospheric Winds', 'Significant Wave Height', 'Ocean Swell Interaction', 'Hydrographic Risk Zone']
    },
    riskLevel: 'MODERATE',
    riskScore: 56,
    riskSummary: 'Moderate marine risk driven by choppy 1.6–2.1m swell and sustained 18–24 kt ENE winds. Manageable for motorized mechanized craft; elevated risk for unmotorized country boats.',
    confidence: 82,
    confidenceFactors: [
      { name: 'Multi-Source Agreement', score: 86, weight: '35%', description: 'Oceansat-3 wind field aligns within 1.2 kt of SWAN coastal wave model' },
      { name: 'Spatial Data Density', score: 84, weight: '25%', description: 'High-density coverage via DWR Paradip and CB-02 in-situ buoy' },
      { name: 'Temporal Recency', score: 89, weight: '25%', description: 'All synthetic assimilation inputs refreshed within last 20 minutes' },
      { name: 'Model Determinism', score: 71, weight: '15%', description: 'Slight uncertainty around coastal wind wave vs southern swell cross-chop' }
    ],
    headline: 'MODERATE CAUTION ADVISED FOR COASTAL FISHING',
    executiveSummary: 'Moderate caution is advised for fishing operations off Paradip tomorrow morning. While no severe cyclonic or squall hazard is identified in satellite and radar streams, sustained 18–24 knot winds and 1.6–2.1 meter choppy seas will create uncomfortable and potentially hazardous rolling for smaller vessels.',
    recommendation: 'Proceed only with caution and monitor the latest marine advisory before departure. Small motorized and non-motorized craft should remain within 5 nautical miles of the coastline.',
    keyFindings: [
      'Moderate wave conditions: Significant wave height (Hs) 1.6m – 2.1m with period 7.8s – 8.4s.',
      'Elevated wind speed: Sustained 18 – 24 knots from ENE with gusts up to 26 knots around 08:30 IST.',
      'Generally manageable visibility: Horizontal visibility 8 – 10 km; low probability of sea fog.',
      'No severe marine hazard signal: No cyclonic depression, gale warning, or high storm surge identified.'
    ],
    workflowSteps: [
      { id: 'step-1', name: 'Query Parsing & Context Extraction', agent: 'Orchestrator Agent', status: 'completed', timestamp: '0.2s', detail: 'Identified entity: Paradip (Odisha), Time: Tomorrow Morning, Activity: Marine Fishing', agentRole: 'orchestrator' },
      { id: 'step-2', name: 'Spatial-Temporal Decomposition', agent: 'Task Planner', status: 'completed', timestamp: '0.6s', detail: 'Decomposed request into 3 parallel intelligence tasks: Weather, Ocean State, Bathymetry', agentRole: 'orchestrator' },
      { id: 'step-3', name: 'Atmospheric Wind & Gust Retrieval', agent: 'Weather Agent', status: 'completed', timestamp: '1.1s', detail: 'Retrieved Oceansat-3 scatterometer & IMD DWR radar wind fields: 18-24 kt ENE', agentRole: 'weather' },
      { id: 'step-4', name: 'Swell & Hydrodynamic Modeling', agent: 'Ocean Agent', status: 'completed', timestamp: '1.5s', detail: 'Computed INCOIS SWAN wave model: Hs 1.85m, peak period 8.2s, cross-swell chop', agentRole: 'ocean' },
      { id: 'step-5', name: 'Navigational & Coastline GIS Analysis', agent: 'Geospatial Agent', status: 'completed', timestamp: '1.9s', detail: 'Mapped 0-12 NM coastal fishing corridor against NHO bathymetry and sandbar shoals', agentRole: 'geospatial' },
      { id: 'step-6', name: 'Multi-Source Evidence Fusion', agent: 'Fusion Engine', status: 'completed', timestamp: '2.3s', detail: 'Fused 5 data streams; verified sensor consistency index at 86%', agentRole: 'synthesizer' },
      { id: 'step-7', name: 'Deterministic Marine Safety Indexing', agent: 'Risk Engine', status: 'completed', timestamp: '2.6s', detail: 'Calculated composite hazard index: 56/100 (MODERATE). Formulated vessel safety thresholds', agentRole: 'risk' },
      { id: 'step-8', name: 'Confidence & Advisory Synthesis', agent: 'Response Synthesizer', status: 'completed', timestamp: '2.9s', detail: 'Evaluated evidence confidence at 82%; generated executive briefing and recommendation', agentRole: 'synthesizer' }
    ],
    agentDialogue: [
      { id: 'ad-1-1', sender: 'Orchestrator', recipient: 'Task Planner', message: 'User Query parsed: "Is it safe to fish near Paradip tomorrow morning?". Entity extracted: Paradip, Odisha (20.26°N, 86.67°E), Window: Tomorrow 05:00-11:30 IST. Initiating parallel specialist subtasks.', timestamp: '0.2s', status: 'verified' },
      { id: 'ad-1-2', sender: 'Weather Agent', recipient: 'Orchestrator', message: 'OSCAT-3 scatterometer pass over North Bay ingested. Sustained 18–24 kt ENE wind field detected with localized morning gusts to 26 kt around 08:30 IST. Cloud cover light stratiform; horizontal visibility 8–10 km.', timestamp: '1.1s', status: 'verified' },
      { id: 'ad-1-3', sender: 'Ocean Agent', recipient: 'Orchestrator', message: 'INCOIS SWAN wave model boundary updated. Significant wave height (Hs) 1.6m – 2.1m with 8.2s peak period. Cross-sea swell interaction with coastal wind wave creates moderate surface chop.', timestamp: '1.5s', status: 'verified' },
      { id: 'ad-1-4', sender: 'Geospatial Agent', recipient: 'Orchestrator', message: 'Mapped 0-12 NM coastal fishing corridor against NHO bathymetry. Sand spit shoaling active up to 1.8 NM east of False Point; inner 5 NM zone remains partially sheltered by shoreline curvature.', timestamp: '1.9s', status: 'verified' },
      { id: 'ad-1-5', sender: 'Risk Engine', recipient: 'Response Synthesizer', message: 'Composite Marine Hazard Index computed: 56/100 (MODERATE). Deterministic threshold exceeded for non-motorized craft. Motorized vessels safe with caution.', timestamp: '2.6s', status: 'verified' },
      { id: 'ad-1-6', sender: 'Response Synthesizer', recipient: 'Orchestrator', message: 'Synthesized executive briefing. Answer Confidence evaluated at 82% across 5 corroborating observation feeds. Formulated operational advisory.', timestamp: '2.9s', status: 'verified' }
    ],
    evidence: paradipEvidenceSources,
    chartType: 'wave_wind_time',
    chartData: [
      { time: '04:00 IST', waveHeight: 1.4, windSpeed: 16, gustSpeed: 19, riskScore: 44 },
      { time: '06:00 IST', waveHeight: 1.6, windSpeed: 18, gustSpeed: 21, riskScore: 52 },
      { time: '08:00 IST', waveHeight: 1.9, windSpeed: 22, gustSpeed: 25, riskScore: 61 },
      { time: '10:00 IST', waveHeight: 2.1, windSpeed: 24, gustSpeed: 27, riskScore: 64 },
      { time: '12:00 IST', waveHeight: 1.8, windSpeed: 20, gustSpeed: 23, riskScore: 55 },
      { time: '14:00 IST', waveHeight: 1.7, windSpeed: 17, gustSpeed: 20, riskScore: 49 },
      { time: '16:00 IST', waveHeight: 1.5, windSpeed: 15, gustSpeed: 18, riskScore: 43 },
      { time: '18:00 IST', waveHeight: 1.4, windSpeed: 14, gustSpeed: 17, riskScore: 40 }
    ],
    mapCenter: [20.2644, 86.6710],
    mapZoom: 11
  },

  scenario2: {
    id: 'scenario2',
    title: 'Offshore Route Corridor Optimization — Kochi',
    chipLabel: 'Vessel route',
    canonicalQuery: 'Which route looks safer for a vessel travelling offshore from Kochi tomorrow?',
    queryAliases: [
      'which route looks safer for a vessel travelling offshore from kochi tomorrow',
      'which route looks safer for a vessel travelling offshore from kochi',
      'which route looks safer for a vessel traveling offshore from kochi tomorrow',
      'which route looks safer for a vessel traveling offshore from kochi',
      'vessel route kochi tomorrow',
      'safer offshore route kochi',
      'route comparison kochi vessel',
      'ship navigation route kochi',
      'cochin vessel route tomorrow',
      'safer route kochi',
      'kochi route safer'
    ],
    context: {
      intent: 'Navigational Route Corridor Optimization & Comparative Risk',
      location: 'Kochi Offshore Transit Channels, Arabian Sea (Kerala Coast)',
      coordinates: '9°50\'N – 10°10\'N, 75°50\'E – 76°15\'E',
      timeWindow: 'Tomorrow Full Day (06:00 – 18:00 IST)',
      activity: 'Offshore Commercial / Service Vessel Transit',
      scope: ['Arabian Sea Swell Sheltering', 'Continental Shelf Bathymetry', 'Cross-Current Shear', 'Vessel Roll & ETA Efficiency']
    },
    riskLevel: 'LOW', // Reflecting Route A recommendation
    riskScore: 34,
    riskSummary: 'Comparative corridor evaluation strongly favors Route A (Kochi Inner Shelf Transit) with 34/100 risk score vs Route B (Outer Deep Arabian Sea) with 68/100 risk score.',
    confidence: 87,
    confidenceFactors: [
      { name: 'Malabar Shelf Bathymetry Resolution', score: 94, weight: '35%', description: 'Detailed multibeam NHO survey along inner continental shelf off Fort Kochi' },
      { name: 'Dual-Corridor Wave Differential', score: 89, weight: '30%', description: 'Strong numerical gradient between sheltered 25m contour and open Arabian Sea' },
      { name: 'Model Cross-Validation', score: 85, weight: '20%', description: 'SWAN and Oceansat-3 scatterometer confirm sheltered inner band off Kerala' },
      { name: 'Temporal Route Stability', score: 81, weight: '15%', description: 'Consistent hydrodynamic profile across projected 12-hour transit window' }
    ],
    headline: 'ROUTE A (INNER SHELF TRANSIT) IS SUBSTANTIALLY SAFER THAN ROUTE B',
    executiveSummary: 'Comparative analysis of the two candidate offshore corridors reveals that Route A (Inner Continental Shelf corridor off Kochi) is substantially safer for transit tomorrow. Route A benefits from coastal wave attenuation along the 25m Malabar shelf contour, keeping significant wave heights between 1.2m–1.5m and wind speeds at 14–17 kt. In contrast, Route B (Outer Deep Channel) is directly exposed to unattenuated 2.3m–2.8m Arabian Sea swells with dangerous cross-sea roll resonance.',
    recommendation: 'Adopt Route A (Inner Shelf Transit). Avoid Route B where steep Arabian Sea swells and 28 knot wind gusts exceed standard operational safety thresholds for medium vessels.',
    keyFindings: [
      'Route A Wave Profile: Max wave height of 1.5m vs 2.8m in Route B (46% lower wave energy impact along Malabar shelf).',
      'Wind & Gust Exposure: Route A encounters average 15 kt northwest breeze; Route B faces sustained 23 kt with 28 kt gusts in open Arabian Sea.',
      'Cross-Sea Stability: Route A has near-parallel swell alignment; Route B suffers 52° cross-sea angle causing severe vessel roll.',
      'Transit Efficiency: Route A is 2.4 nautical miles longer but achieves a 24-minute faster, safer transit due to reduced hydrodynamic resistance.'
    ],
    workflowSteps: [
      { id: 'step-1', name: 'Corridor Geometry & Waypoint Ingestion', agent: 'Orchestrator Agent', status: 'completed', timestamp: '0.2s', detail: 'Identified query: Vessel Route Comparison offshore Kochi. Loaded corridors A & B', agentRole: 'orchestrator' },
      { id: 'step-2', name: 'Route Task Decomposition', agent: 'Task Planner', status: 'completed', timestamp: '0.5s', detail: 'Dispatched dual-corridor analysis to Geospatial, Oceanographic, and Weather specialist agents', agentRole: 'orchestrator' },
      { id: 'step-3', name: 'Corridor A & B Weather Exposure', agent: 'Weather Agent', status: 'completed', timestamp: '1.0s', detail: 'Route A wind: 14-17 kt (sheltered by Malabar coast). Route B wind: 21-28 kt (open Arabian Sea fetch)', agentRole: 'weather' },
      { id: 'step-4', name: 'Hydrodynamic Sea State Comparison', agent: 'Ocean Agent', status: 'completed', timestamp: '1.4s', detail: 'Route A Hs: 1.35m (smooth). Route B Hs: 2.55m with severe cross-swell resonance', agentRole: 'ocean' },
      { id: 'step-5', name: 'Bathymetric Shelf & Hazard Mapping', agent: 'Geospatial Agent', status: 'completed', timestamp: '1.8s', detail: 'Verified 20m draft clearance along Kochi Route A; plotted safe navigational polygon', agentRole: 'geospatial' },
      { id: 'step-6', name: 'Cross-Corridor Multi-Factor Scoring', agent: 'Deterministic Analysis', status: 'completed', timestamp: '2.2s', detail: 'Computed composite safety scores: Route A (34/100) vs Route B (68/100)', agentRole: 'risk' },
      { id: 'step-7', name: 'Comparative Evidence Synthesis', agent: 'Confidence Engine', status: 'completed', timestamp: '2.5s', detail: 'Established 87% Answer Confidence based on high spatial agreement along Malabar shelf', agentRole: 'synthesizer' },
      { id: 'step-8', name: 'Vessel Advisory Generation', agent: 'Response Synthesizer', status: 'completed', timestamp: '2.8s', detail: 'Finalized route recommendation matrix and interactive corridor visualization for Kochi', agentRole: 'synthesizer' }
    ],
    agentDialogue: [
      { id: 'ad-2-1', sender: 'Orchestrator', recipient: 'Geospatial Agent', message: 'Vessel route optimization offshore Kochi received. Ingesting corridor geometries for Route A (Inner Shelf Transit) and Route B (Outer Deep Channel) to station X.', timestamp: '0.2s', status: 'verified' },
      { id: 'ad-2-2', sender: 'Geospatial Agent', recipient: 'Weather & Ocean Agents', message: 'Corridor waypoints dispatched: Route A (15.4 NM along 25m Malabar depth contour) vs Route B (17.8 NM along open Arabian Sea shelf break). Requesting hydrodynamic intersection.', timestamp: '0.5s', status: 'verified' },
      { id: 'ad-2-3', sender: 'Weather Agent', recipient: 'Orchestrator', message: 'Atmospheric exposure computed off Kerala: Route A is sheltered by landward boundary (14–17 kt wind). Route B faces sustained 23 kt with 28 kt gusts in open sea fetch.', timestamp: '1.0s', status: 'verified' },
      { id: 'ad-2-4', sender: 'Ocean Agent', recipient: 'Orchestrator', message: 'Wave simulation differential: Route A Hs = 1.35m (smooth parallel swell). Route B Hs = 2.55m with 52° cross-sea angle causing severe vessel roll resonance.', timestamp: '1.4s', status: 'verified' },
      { id: 'ad-2-5', sender: 'Risk Engine', recipient: 'Response Synthesizer', message: 'Corridor Hazard Index evaluated: Route A (34/100, LOW/MODERATE) vs Route B (68/100, ELEVATED). Recommendation: Explicitly endorse Route A for Kochi offshore transit.', timestamp: '2.2s', status: 'verified' },
      { id: 'ad-2-6', sender: 'Response Synthesizer', recipient: 'Orchestrator', message: 'Evidence Confidence confirmed at 87% with high bathymetric survey resolution. Finalized route comparison table and comparative navigational charts.', timestamp: '2.8s', status: 'verified' }
    ],
    evidence: kochiEvidenceSources,
    chartType: 'route_comparison',
    chartData: [
      { time: 'Significant Wave Height (m)', RouteA: 1.35, RouteB: 2.55, unit: 'm' },
      { time: 'Sustained Wind Speed (kt)', RouteA: 15.2, RouteB: 23.6, unit: 'kt' },
      { time: 'Max Wind Gust (kt)', RouteA: 18.0, RouteB: 28.5, unit: 'kt' },
      { time: 'Cross-Sea Risk Index (0-10)', RouteA: 2.1, RouteB: 7.8, unit: 'pts' },
      { time: 'Navigational Hazard Score (0-100)', RouteA: 34.0, RouteB: 68.0, unit: 'score' }
    ],
    routeData: [
      {
        routeId: 'route-a',
        routeName: 'Route A: Inner Shelf Transit (Recommended)',
        distanceNm: 15.4,
        etaHours: 1.4,
        overallRisk: 'LOW',
        riskScore: 34,
        avgWaveHeight: 1.3,
        maxWaveHeight: 1.5,
        avgWindSpeed: 15,
        maxWindGust: 18,
        crossSeaRisk: 'Low',
        recommendation: 'RECOMMENDED',
        summary: 'Sheltered along the 25m Malabar bathymetric contour with minimal cross-swell and 46% lower wave impact.',
        coordinates: [
          [9.9660, 76.2200], // Kochi Port Anchorage
          [10.0100, 76.1200], // Waypoint A1 (Inner Shelf)
          [10.0800, 76.0300], // Waypoint A2
          [10.1500, 75.9400]  // Waypoint A3 (Offshore Destination)
        ]
      },
      {
        routeId: 'route-b',
        routeName: 'Route B: Outer Deep Channel (High Exposure)',
        distanceNm: 17.8,
        etaHours: 1.8,
        overallRisk: 'ELEVATED',
        riskScore: 68,
        avgWaveHeight: 2.4,
        maxWaveHeight: 2.8,
        avgWindSpeed: 23,
        maxWindGust: 28,
        crossSeaRisk: 'High',
        recommendation: 'AVOID',
        summary: 'Direct exposure to unattenuated open Arabian Sea swells with steep wave fronts and strong 28 kt wind gusts.',
        coordinates: [
          [9.9660, 76.2200], // Kochi Port Anchorage
          [9.9200, 76.0800],  // Waypoint B1 (Deep Channel)
          [9.9900, 75.9100],  // Waypoint B2 (Shelf Break)
          [10.1500, 75.9400]  // Waypoint B3 (Offshore Destination)
        ]
      }
    ],
    mapCenter: [10.03, 76.08],
    mapZoom: 10
  },

  scenario3: {
    id: 'scenario3',
    title: 'Marine Hazard & Extreme Weather Evaluation — Visakhapatnam',
    chipLabel: 'Marine hazards',
    canonicalQuery: 'Are there any significant marine hazards expected near Visakhapatnam tomorrow?',
    queryAliases: [
      'are there any significant marine hazards expected near visakhapatnam tomorrow',
      'are there any significant marine hazards near visakhapatnam tomorrow',
      'marine hazards visakhapatnam tomorrow',
      'cyclone warning visakhapatnam',
      'storm warning visakhapatnam tomorrow',
      'visakhapatnam marine hazards',
      'danger at sea visakhapatnam',
      'vizag marine hazards tomorrow',
      'is there any cyclone near vizag tomorrow',
      'marine hazards vizag',
      'visakhapatnam hazards'
    ],
    context: {
      intent: 'Comprehensive Marine Hazard Detection & Threat Assessment',
      location: 'Visakhapatnam Port & Coastal Maritime Zone, Andhra Pradesh',
      coordinates: '17.30°N – 17.85°N, 83.10°E – 83.55°E',
      timeWindow: 'Tomorrow Full 24-Hour Cycle (00:00 – 23:59 IST)',
      activity: 'Marine Operations, Port Navigation & Coastal Safety',
      scope: ['Tropical Cyclogenesis', 'Storm Surge Anomaly', 'Dolphin\'s Nose Headland Rip Currents', 'Squall Reflectivity', 'Tsunami / Seismic']
    },
    riskLevel: 'MODERATE',
    riskScore: 48,
    riskSummary: 'No severe cyclonic, storm surge, or extreme weather hazard signal detected. Moderate marine conditions (1.7m waves, localized tidal rip currents near Dolphin\'s Nose) require standard maritime vigilance.',
    confidence: 79,
    confidenceFactors: [
      { name: 'Multi-Satellite Cyclogenesis Scan', score: 88, weight: '35%', description: 'INSAT-3DR & Oceansat-3 confirm no low-pressure vortex in Central Bay of Bengal' },
      { name: 'Doppler Radar Storm Tracking', score: 82, weight: '25%', description: 'IMD Kailasagiri DWR confirms clear reflectivity below 26 dBZ' },
      { name: 'Headland Current Modeling', score: 74, weight: '25%', description: 'Tidal discharge at Dolphin\'s Nose headland shows localized rip risk' },
      { name: 'Extended 24h Prediction Horizon', score: 68, weight: '15%', description: 'Slight convective variance anticipated towards late evening' }
    ],
    headline: 'NO SEVERE MARINE HAZARDS DETECTED — MODERATE CAUTION WARRANTED',
    executiveSummary: 'Comprehensive multi-sensor screening confirms that NO major severe marine hazard signals (such as tropical cyclones, depressions, tsunami anomalies, or storm surges) are active or expected near Visakhapatnam tomorrow. However, ambient marine conditions remain moderate, featuring 1.6m–2.0m waves and localized rip currents near the Dolphin\'s Nose headland and Rishikonda.',
    recommendation: 'Normal commercial navigation permitted under standard port protocol. Small craft and fishing vessels should maintain caution regarding localized rip currents near Dolphin\'s Nose headland and moderate wave chop beyond 6 nautical miles.',
    keyFindings: [
      'No Cyclonic Activity: Zero tropical depression or cyclonic circulation signals detected across Central Bay of Bengal by ISRO/IMD.',
      'Normal Astronomical Tide: Predicted tide range +1.3m to -0.1m with zero storm surge anomaly (+0.06m at Visakhapatnam Outer Harbour).',
      'Headland Rip Current Advisory: Moderate localized rip currents identified near Dolphin\'s Nose and Rishikonda during ebbing tide (09:30–12:45 IST).',
      'Offshore Sea State: Ambient significant wave height 1.6m–2.0m with 8.5s swell period; no extreme squall or freak wave signature.'
    ],
    workflowSteps: [
      { id: 'step-1', name: 'Hazard Entity & Threat Spectrum Ingestion', agent: 'Orchestrator Agent', status: 'completed', timestamp: '0.2s', detail: 'Initialized 5-tier threat evaluation for Visakhapatnam: Cyclones, Surges, Squalls, Rip Currents, Obstructions', agentRole: 'orchestrator' },
      { id: 'step-2', name: 'Multi-Agency Alert Query', agent: 'Task Planner', status: 'completed', timestamp: '0.5s', detail: 'Polled IMD Cyclone Warning Centre Vizag, INCOIS High Wave Alert System, and Tsunami Warning Center', agentRole: 'orchestrator' },
      { id: 'step-3', name: 'Atmospheric Convection & Vortex Analysis', agent: 'Weather Agent', status: 'completed', timestamp: '1.0s', detail: 'INSAT-3DR thermal infrared and Kailasagiri DWR radar confirm absent cyclonic vorticity', agentRole: 'weather' },
      { id: 'step-4', name: 'Ocean Hydrodynamics & Sea Floor Bathymetry', agent: 'Ocean Agent', status: 'completed', timestamp: '1.5s', detail: 'Calculated wave runup and Dolphin\'s Nose headland discharge: 1.2 m/s localized rip hazard', agentRole: 'ocean' },
      { id: 'step-5', name: 'Geospatial Hazard Polygon Generation', agent: 'Geospatial Agent', status: 'completed', timestamp: '1.9s', detail: 'Demarcated yellow advisory zone at Dolphin\'s Nose & Rishikonda; green clearance for main shipping roadstead', agentRole: 'geospatial' },
      { id: 'step-6', name: 'Threat Fusion & Matrix Evaluation', agent: 'Fusion Engine', status: 'completed', timestamp: '2.3s', detail: 'Combined multi-sensor vectors for Vizag: 0 severe alerts, 1 local headland advisory', agentRole: 'risk' },
      { id: 'step-7', name: 'Confidence Score Formulation', agent: 'Confidence Engine', status: 'completed', timestamp: '2.6s', detail: 'Assessed 79% Evidence Confidence across integrated observation layers', agentRole: 'synthesizer' },
      { id: 'step-8', name: 'Marine Advisory Briefing Synthesis', agent: 'Response Synthesizer', status: 'completed', timestamp: '2.9s', detail: 'Synthesized executive threat briefing and Visakhapatnam port maritime protocols', agentRole: 'synthesizer' }
    ],
    agentDialogue: [
      { id: 'ad-3-1', sender: 'Orchestrator', recipient: 'Weather Agent', message: 'Hazard query received: "Are there any significant marine hazards expected near Visakhapatnam tomorrow?". Initiating full 5-tier threat screening.', timestamp: '0.2s', status: 'verified' },
      { id: 'ad-3-2', sender: 'Weather Agent', recipient: 'Orchestrator', message: 'Satellite & radar cyclogenesis audit completed for Andhra coast. INSAT-3DR thermal infrared and Kailasagiri DWR radar confirm absent cyclonic vorticity. Zero gale or squall alerts within 500 km.', timestamp: '1.0s', status: 'verified' },
      { id: 'ad-3-3', sender: 'Ocean Agent', recipient: 'Geospatial Agent', message: 'Tidal surge variance nominal (+0.06m at Vizag Outer Harbour). However, headland outflow modeling reveals 1.2 m/s localized rip currents around Dolphin\'s Nose during morning ebbing tide (09:30–12:45 IST).', timestamp: '1.5s', status: 'verified' },
      { id: 'ad-3-4', sender: 'Geospatial Agent', recipient: 'Risk Engine', message: 'Demarcated yellow advisory polygon for Dolphin\'s Nose and Rishikonda coastal buffers. Main Visakhapatnam commercial navigation roadstead cleared as green/nominal.', timestamp: '1.9s', status: 'verified' },
      { id: 'ad-3-5', sender: 'Risk Engine', recipient: 'Response Synthesizer', message: 'Threat matrix resolved for Visakhapatnam: 0 severe hazards, 1 localized headland rip advisory. Composite index: 48/100 (MODERATE CAUTION).', timestamp: '2.3s', status: 'verified' },
      { id: 'ad-3-6', sender: 'Response Synthesizer', recipient: 'Orchestrator', message: 'Synthesized 24-hour diurnal hazard breakdown for Visakhapatnam. Answer Confidence rated at 79%. Formulated port navigation clearance.', timestamp: '2.9s', status: 'verified' }
    ],
    evidence: vizagEvidenceSources,
    chartType: 'hazard_timeline',
    chartData: [
      { time: '00:00 - 06:00 (Night)', riskScore: 36, waveHeight: 1.4, currentSpeed: 0.4, windSpeed: 14 },
      { time: '06:00 - 09:00 (Early AM)', riskScore: 44, waveHeight: 1.6, currentSpeed: 0.8, windSpeed: 16 },
      { time: '09:00 - 12:00 (Rip Peak)', riskScore: 54, waveHeight: 1.9, currentSpeed: 1.2, windSpeed: 20 },
      { time: '12:00 - 15:00 (Afternoon)', riskScore: 50, waveHeight: 1.8, currentSpeed: 0.9, windSpeed: 18 },
      { time: '15:00 - 18:00 (Late Day)', riskScore: 44, waveHeight: 1.6, currentSpeed: 0.6, windSpeed: 16 },
      { time: '18:00 - 24:00 (Evening)', riskScore: 38, waveHeight: 1.3, currentSpeed: 0.4, windSpeed: 13 }
    ],
    hazards: [
      { id: 'h-1', type: 'Tropical Cyclone / Depression', severity: 'Advisory', status: 'Clear / None Detected', location: 'Central Bay of Bengal', details: 'No low-pressure system or convective circulation detected within 500 km of Visakhapatnam.', icon: 'CheckCircle' },
      { id: 'h-2', type: 'Storm Surge & Tidal Anomaly', severity: 'Advisory', status: 'Normal Astronomical', location: 'Visakhapatnam Outer Harbour', details: 'Surge variance < 0.08m. Astronomical high tide of 1.7m at 11:30 IST.', icon: 'CheckCircle' },
      { id: 'h-3', type: 'Headland Rip Currents', severity: 'Watch', status: 'Moderate Advisory', location: 'Dolphin\'s Nose & Rishikonda', details: 'Ebb tide discharge around headland creates localized rip current shear (1.1–1.3 m/s) between 09:30–12:45 IST.', icon: 'AlertTriangle' },
      { id: 'h-4', type: 'Offshore Sea State & Swell', severity: 'Watch', status: 'Moderate Waves (1.8m)', location: 'Open Shelf (>6 NM)', details: 'Long-period south-southeasterly swell crosses local wind chop; manageable for commercial vessels.', icon: 'AlertTriangle' }
    ],
    mapCenter: [17.6868, 83.3040],
    mapZoom: 11
  }
};
